export const ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  FORBIDDEN_NOT_MEMBER: 'FORBIDDEN_NOT_MEMBER',
  FORBIDDEN_NOT_OWNER: 'FORBIDDEN_NOT_OWNER',
  SPACE_NOT_FOUND: 'SPACE_NOT_FOUND',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  INVALID_INVITATION_TOKEN: 'INVALID_INVITATION_TOKEN',
  INVITATION_EMAIL_MISMATCH: 'INVITATION_EMAIL_MISMATCH',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  CANNOT_REMOVE_LAST_OWNER: 'CANNOT_REMOVE_LAST_OWNER',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_TAKEN: 'CATEGORY_NAME_TAKEN',
  INVALID_REORDER: 'INVALID_REORDER',
  CURRENCY_API_UNAVAILABLE: 'CURRENCY_API_UNAVAILABLE',
  CURRENCY_NOT_SUPPORTED: 'CURRENCY_NOT_SUPPORTED',
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  INVALID_OCCURRED_AT: 'INVALID_OCCURRED_AT',
  INVALID_RECURRING_DATE_RANGE: 'INVALID_RECURRING_DATE_RANGE',
  WALLET_ARCHIVED: 'WALLET_ARCHIVED',
  CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',
  INVALID_PERIOD: 'INVALID_PERIOD',
  RECURRING_NOT_FOUND: 'RECURRING_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

// Codes produced by AppExceptionFilter for exceptions that are not
// AppExceptions (class-validator, passport, throttler, unexpected errors).
export const GENERIC_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type GenericErrorCode =
  (typeof GENERIC_ERROR_CODES)[keyof typeof GENERIC_ERROR_CODES];

export type ApiErrorCode = ErrorCode | GenericErrorCode;
